### ISSUE TITLE
Issue with make

### ISSUE THREAD

**Issue by sherkon18** [skaringa/emeocv#1]
g++ -Wno-write-strings -I . -g -D _DEBUG -c KNearestOcr.cpp -o Debug/KNearestOcr.o
In file included from KNearestOcr.cpp:18:0:
KNearestOcr.h:36:5: error: ‘CvKNearest’ does not name a type
     CvKNearest\* _pModel;
     ^
KNearestOcr.cpp: In constructor ‘KNearestOcr::KNearestOcr(const Config&)’:
KNearestOcr.cpp:21:9: error: class ‘KNearestOcr’ does not have any field named ‘_pModel’
         _pModel(0), _config(config) {
         ^
KNearestOcr.cpp: In destructor ‘virtual KNearestOcr::~KNearestOcr()’:
KNearestOcr.cpp:25:9: error: ‘_pModel’ was not declared in this scope
     if (_pModel) {
         ^
KNearestOcr.cpp:26:16: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
         delete _pModel;
                ^
KNearestOcr.cpp: In member function ‘char KNearestOcr::recognize(const cv::Mat&)’:
KNearestOcr.cpp:90:14: error: ‘_pModel’ was not declared in this scope
         if (!_pModel) {
              ^
KNearestOcr.cpp:94:24: error: ‘_pModel’ was not declared in this scope
         float result = _pModel->find_nearest(prepareSample(img), 2, results, neighborResponses, dists);
                        ^
KNearestOcr.cpp: In member function ‘void KNearestOcr::initModel()’:
KNearestOcr.cpp:137:5: error: ‘_pModel’ was not declared in this scope
     _pModel = new CvKNearest(_samples, _responses);
     ^
KNearestOcr.cpp:137:19: error: expected type-specifier before ‘CvKNearest’
     _pModel = new CvKNearest(_samples, _responses);
                   ^
KNearestOcr.cpp:137:19: error: expected ‘;’ before ‘CvKNearest’
make: **\* [Debug/KNearestOcr.o] Error 1

**Comment by skaringa** [comment]
You are probably using the wrong version of OpenCV  or didn't install it at all.

**Comment by Ankit09** [comment]
I am facing the same error,
I have installed OpenCV correctly. 
Help me out.
