### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by amir-hg** [skaringa/emeocv#11]
hi
when I try to build with make I got this error
kubuntu 18.04 LTS

g++ -Wno-write-strings -I . `pkg-config opencv --cflags` -g -D _DEBUG  Debug/Directory.o Debug/Config.o Debug/ImageProcessor.o Debug/ImageInput.o Debug/KNearestOcr.o Debug/Plausi.o Debug/RRDatabase.o Debug/main.o `pkg-config opencv --libs` -lrrd -llog4cpp -o Debug/emeocv
/usr/bin/ld: /usr/local/lib/libopencv_videoio.a(cap_ffmpeg.cpp.o): undefined reference to symbol 'pthread_spin_trylock@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:44: recipe for target 'Debug/emeocv' failed
make: *** [Debug/emeocv] Error 1

**Comment by skaringa** [comment]
I can't reproduce this on Ubuntu 18.04.
You may try to add -lpthread to the LDLIBS variable in the Makefile.

**Comment by amir-hg** [comment]
It does not still work i tried so many ways to add libs
Which ubuntu did you test it and run it sucessfully
Or any distro of linux

**Comment by skaringa** [comment]
It seams that you use your own opencv installation in /usr/local/lib instead of opencv included in the distribution. So you have to configure you linker correctly, e.g. by setting LD_LIBRARY_PATH  to /usr/local/lib.
