### ISSUE TITLE
std::out_of_range when training

### ISSUE THREAD

**Issue by ElDavoo** [skaringa/emeocv#15]
Hello, I compiled emeocv with a freshly installed debian 9, but when I try to train it crashes.
$ Debug/emeocv -i png/ -l
Entering OCR training mode!
<0>..<9> to answer.....quit without saving.
terminate called after throwing an instance of 'std::out_of_range'
  what(): basic_string::substr: __pos (which is 9) > this->size() (which is 7)
Aborted
$

Feel free to ask for more details if needed

**Comment by zz04303** [comment]
possibly because your input filename is not like 20190109-001006.png

**Comment by ElDavoo** [comment]
Thank you! That's Crazy! These errors should be handled better.

Il giorno sab 12 gen 2019, 19:54 nl04303 <notifications@github.com> ha
scritto:

**Comment by skaringa** [comment]
emeocv uses filename pattern **%Y%m%d-%H%M%S.png** for both capturing and ocr. If you use another program to capture the files, then you have to ensure that filenames follow this pattern too.

**Comment by sve95** [comment]
Thanks so much for the quick response. 
BR Sergio 


От: "skaringa" <notifications@github.com> 
Кому: "skaringa/emeocv" <emeocv@noreply.github.com> 
Копия: "Subscribed" <subscribed@noreply.github.com> 
Отправленные: Понедельник, 28 Январь 2019 г 19:14:25 
Тема: Re: [skaringa/emeocv] std::out_of_range when training (#15) 



emeocv uses filename pattern %Y%m%d-%H%M%S.png for both capturing and ocr. If you use another program to capture the files, then you have to ensure that filenames follow this pattern too.
