### ISSUE TITLE
no executable found

### ISSUE THREAD

**Issue by skyw43** [skaringa/emeocv#19]
Hi,
Thanks for this very interesting project and all the work done. I'm  Sorry for the maybe stupid question but I followed tutorial to install emeocv. After the final "make" step, I can't execute the emeocv executable file as it seems to be not found. I tried to "locate" it but not found. I tested both on raspbian stretch & debian 5.2.9 without success. Did I miss something to be prepared in the environment ?
Thanks in advance for the support
Skyw43

**Comment by skaringa** [comment]
The emeocv executable is produced in the emeocv/Debug folder.
So if you are sitting in the emeocv directory, then use Debug/emeocv to run the program.

**Comment by Gafaddi** [comment]
> The emeocv executable is produced in the emeocv/Debug folder.
> So if you are sitting in the emeocv directory, then use Debug/emeocv to run the program.

I still cannot run the emeocv . could you olease help me , I have everything installed .

**Comment by Gafaddi** [comment]
> Hi,
> Thanks for this very interesting project and all the work done. I'm Sorry for the maybe stupid question but I followed tutorial to install emeocv. After the final "make" step, I can't execute the emeocv executable file as it seems to be not found. I tried to "locate" it but not found. I tested both on raspbian stretch & debian 5.2.9 without success. Did I miss something to be prepared in the environment ?
> Thanks in advance for the support
> Skyw43

Any update ?

**Comment by dstamou** [comment]
@Gafaddi you run emeocv with following command ./emeocv
