### ISSUE TITLE
Error when learning the digits

### ISSUE THREAD

**Issue by spidgorny** [skaringa/emeocv#2]
I'm trying to reproduce the whole process according to your tutorial. BTW, thank you - it's awesome.

When doing `./emeocv -i . -l -v DEBUG` I get

```
OpenCV Error: Bad argument (train data must be floating-point matrix) in cvCheckTrainData, file /build/opencv-92Ozt2/opencv-2.4.9.1+dfsg/modules/ml/src/inner_functions.cpp, line 857
terminate called after throwing an instance of 'cv::Exception'
what():  /build/opencv-92Ozt2/opencv-2.4.9.1+dfsg/modules/ml/src/inner_functions.cpp:857: error: (-5) train data must be floating-point matrix in function cvCheckTrainData
```

My `trainctr.yml` file looks too simple.
```
%YAML:1.0
samples: !!opencv-matrix
   rows: 0
   cols: 0
   dt: u
   data: []
responses: !!opencv-matrix
   rows: 0
   cols: 0
   dt: u
   data: []
```

Any help is appreciated.
P.S. I've only used your single example image for training. I've not setup my Rpi webcam yet.

**Comment by skaringa** [comment]
This happens when you started training mode before but didn't train any data.
Simply delete the empty trainctr.yml and start again with real data.

**Comment by qt1211** [comment]
Hi @skaringa, I got the same problem. I've been training 7 samples. I already deleted the trainctr.yml and ran "emeocv -i images -l" to train again but i still got the empty data. Can I ask what did you mean by "real data"? Did you mean we need to use 447 samples data? Thanks a lot for the great project.

**Comment by skaringa** [comment]
It seems that sometimes waitKey() sets extra bits in the return value: https://stackoverflow.com/questions/36860683/opencv-cvwaitkey-return-value
In this case, the learning window doesn't work. I will fix this.
