### ISSUE TITLE
Keyboard action not détected.

### ISSUE THREAD

**Issue by zekirma** [skaringa/emeocv#22]
I installed it on a Raspberry Zero and I control it with vnc. 
When I start the first command 'emeocv -c0 -a -s10 -vINFO' it is impossible to have a action via the keyboard ( VNC) . If I push S Q or whatelse, I see the caracters but it have so action. The only thing working is ctrl-c.
So it was impossible to save the training file and after a got naturelly 'pi@raspberrypi:~/emeocv/Debug $ ./emeocv -i /home/pi/emeocv/images -t -s0
'Failed to load OCR training data' error message. 
How can resolve this?

**Comment by skaringa** [comment]
I don't know anything about vnc.
It works well within a desktop environment, like kde or lxde. 
My best guess is that your emeocv window doesn't have the keyboard focus. You should click with the mouse into the image window so that it gets the keyboard input instead of the terminal window.
