### ISSUE TITLE
Einzelne Zahl wird teilweise nicht als Zahl erkannt

### ISSUE THREAD

**Issue by Caliban2017** [skaringa/emeocv#25]
Hallo, ich hoffe es ist okay wenn ich auf Deutsch schreibe, da Ihre Anleitung ja auch auf Deutsch ist. Erstmal möcht ich mich bedanken für die großartige Arbeit mit diesem Programm. Ich habe es als erstes mal mit diesen Arduino Infrarot Lichtschranken versucht die Drehscheibe am Zähler auszulesen aber nachdem das vorn und hinten nicht zuverlässig funktioniert hat, kam ich auf die Idee OCR zu nutzen, da ich noch eine alte IP Kamera liegen hatte. Das Tool hier ist also echt perfekt für meinen Anspruch.

Ich nutze einen Raspberry Pi 3 und der aktuellsten Raspbian Version. Die Installation war kein Problem und nach etwas ausprobieren, habe ich auch das Auslesen zum starten bekommen. Nach dem Anpassen der Canny-Werte waren die Zahlen auch schon ganz gut erkennbar. Nun bin ich gerade am anlernen der OCR Software, stelle aber immer wieder fest das mein Zählerstand nur so zu 70% voll ausgelesen wird. Mein Zählerstand ist 5-Stellig, als Beispiel ist der Zählerstand 1 3 4 6 5, die Software legt dann aber oft nur Boxen um 1 3 _ 6 5. Da wird dann zb die 4 nicht erkannt, obwohl die angelernt ist und auch genau so sichtbar und auf gleicher Höhe wie die anderen Zahlen.  Das merkwürdige nun daran, teste ich es mit einem gleichen Bild ein paar Sekunden später geschossen, dann erkennt er plötzlich alle Zahlen. Obwohl das Bild in diesem Sinne genau gleich ist, vlt ist das Kamera-Rauschen ein wenig anders. Woran könnte das liegen? Sind das noch immer keine optimalen Canny Werte? Ich hab es auch mit diesem OCR Distanz Wert in der Config rumprobiert, da kann ich aber werte eintragen will ich will, das ändert gar nichts am auslesen. Gibt es eine Möglichkeit diese Canny-Werte irgendwie optisch sichtbar zu machen? So wie auf den Bildern in Ihrer Anleitung? Ich hab es mit dem -a Startparameter versucht, leider geht dann aber nur kurz das Bild auf, geht nach ein oder zwei Sekunden aber direkt wieder zu. Es ist im Moment nur ein Glücksspiel, wenn ich die Canny Werte abändere, ich weiss in diesem Sinne nicht was ich genau da ändere, ich sehe die Änderungen nur beim anlernen, wenn das Programm die einzelnen Zahlen erkennt (oder eben bei falschen Werten auch nicht). 

Würde mich sehr über eine Antwort freuen, find das Programm echt super und möchte es später dann gerne nutzen um meine Zählerstände an OpenHab zu übertragen. Natürlich könnt ich mir noch eine Lösung einfallen lassen, dass eine weitere Prüfung stattfindet ob der ausgelesene Wert plausibel und korrekt ist aber toller wäre es natürlich, wenn ich die Erkennung noch optimieren kann. 

Vielleicht gibt es noch zwei andere Fehlerquellen, die an der Kamera liegen. Zum einen hat die Kamera einen deutlich sichtbaren Fish-eye Effekt. Nicht so schlimm wie bei einer Actioncam aber an den Rändern wölben sich schon ein wenig Quadratische Boxen im Bild. Und zum anderen steht die Kamera relativ nah dran an dem Zähler, damit die Zahlen besser erkannt werden können. Aber vielleicht ist das gerade ja das Problem?

Hier mal ein Beispielbild, von einem Snapshot der ausgewertet werden soll.
![P21031822044410](https://user-images.githubusercontent.com/32013635/111694035-a486ba00-8831-11eb-83c0-5aa25234cad2.jpg)

Vielen Dank erstmal und viele Grüße

**Comment by Caliban2017** [comment]
Hier noch mal als Nachtrag ein Bild der erkennung. Wie man sieht lässt er hier die 5 am Ende aus, obwohl sie eig gut sichtbar ist. Und manchmal lässt er eben auch Zahlen in der Mitte weg.
![screen1](https://user-images.githubusercontent.com/32013635/111694512-43abb180-8832-11eb-954f-4d1886395640.JPG)

**Comment by skaringa** [comment]
Das Erkennen der Bounding Boxes findet in den Funktionen findAlignedBoxes() und filterContours() statt. Möglicherweise hilft es, mit den dort verwenden Konfigurationsparametern zu experimentieren: digitMinHeight, digitMaxHeight, digitYAlignment

**Comment by Caliban2017** [comment]
Okay, ich habe jetzt ein wenig mit der digitYAligment gespielt und etwas erhöht, nun erkennt er im Moment fast fehlerlos alle Zahlen. Ich habe mir einfach ein paar Scripte geschrieben um ein paar Snapshots hintereinander zu machen, diese alle auszuwerten und in der Regel ist so bei 5 Bildern ein gültiger Wert dabei. Da ich meine Zählerstand nur alle 24h einmal automatisch ablesen lassen möchte für nen Tagesverbrauch, ist diese Lösung nun wirklich perfekt! Vielen Dank noch mal für die Arbeit an dieser Software und viele Grüße.
