### ISSUE TITLE
Lediglich Terminalausgaben, 

### ISSUE THREAD

**Issue by D-c8** [skaringa/emeocv#26]
Hallo,

ich habe folgendes Problem:
Ich habe die Befehle wie folgt eingegeben:
![image](https://user-images.githubusercontent.com/98453061/151163572-a1c3246e-0eb8-412d-b0eb-6f2207a7fbd6.png)
Allerdings ist nie mehr passiert als diese Ausgabe.
Es wurden keinen Fenster geöffnet, nichts in die Datenbank eingetragen und in das angegebene Verzeichnis wurde auch nichts gespeichert.

Ich habe wie in der Dokumentation OpenCV-2.3.1 installiert und benutze Raspian 11 (bullseye).

Vielen Dank im voraus.

**Comment by skaringa** [comment]
Hinter -i muss der Pfad zu einem Directory stehen, nicht zu einer Datei.


```
Image input:
    -i <image directory> : read image files (png) from directory.
```

**Comment by D-c8** [comment]
Erstmal vielen Dank für die schnelle Antwort.

Das hatte ich davor auch ausprobiert, allerdings tritt dann folgender Fehler auf:
![image](https://user-images.githubusercontent.com/98453061/151337086-b9674ec1-7ba4-4400-a354-b70273050555.png)
Deswegen dachte ich der Pfad zu einer Datei ist richtig, da kein Fehler angezeigt wurde.

**Comment by skaringa** [comment]
Die Dateinamen müssen einem bestimmten Muster folgen. Details im Sourcecode https://github.com/skaringa/emeocv/blob/6f3ada4a1b3f15fc5dcbd602a557f06f2be11f76/ImageInput.cpp#L38
