### ISSUE TITLE
Unable to init server: Could not connect: Connection refused

### ISSUE THREAD

**Issue by holzfelix** [skaringa/emeocv#28]
After fixed the not working camera issues I got a new error. I run the following command:

`sudo ./emeocv -c 0 -l`

Then I got the follwoing error:

```
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (1824) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module v4l2src0 reported: Internal data stream error.
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (914) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (501) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
Unable to init server: Could not connect: Connection refused
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.1) ../modules/highgui/src/window_gtk.cpp:624: error: (-2:Unspecified error) Can't initialize GTK backend in function 'cvInitSystem'

Aborted
```

What is my issue in this case?
Thanks in advance

**Comment by holzfelix** [comment]
same issue when I run 
`sudo ./emeocv -c 0 -a`

**Comment by skaringa** [comment]
This is not an issue of emeocv. It is probably caused by some misconfiguration of your system (X11 not installed, DISPLAY not set, camera not recognized, etc.). You may search the internet for the errors produced by GStreamer and GTK and will find a lot of hints.

**Comment by holzfelix** [comment]
Hm I changed the camera, and now I got this issue

[ WARN:0] global ../modules/videoio/src/cap_gstreamer.cpp (961) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
Unable to init server: Could not connect: Connection refused

I use a Logitech c920 usb cam
