### ISSUE TITLE
OCR low quality with 10x10 matrix

### ISSUE THREAD

**Issue by spidgorny** [skaringa/emeocv#3]
Hi,

in my case, the quality of OCR is very low. After training 447 samples I only get one correct digit in 100.

This is a visualization of my training data.
![](https://cloud.githubusercontent.com/assets/1579235/26342073/de40bbca-3f96-11e7-840a-fab7a294fd1d.png)

I've noticed that it's hard even for a human to recognize the shapes quickly and reliably. What can we do to improve the quality of OCR?

My only idea was to increase the sample size to 25x15 and try again. Please let me know if there's an easier way.

My original source image is well lit and adjusted to fit the screen.
![](https://github.com/spidgorny/energy-monitor/raw/master/images/IMG_20170515_231615.jpg)

**Comment by nor500** [comment]
Did you have success with that?

**Comment by spidgorny** [comment]
Yes and no. I tried changing something in this project but failed miserably with C++ and reprogrammed everything in Python here: https://github.com/spidgorny/energy-monitor
Check the readme file - it's pretty detailed. I've also increased the matrix size to 30x15 and it WORKS!
