### ISSUE TITLE
OCR problem with 0/8

### ISSUE THREAD

**Issue by spidgorny** [skaringa/emeocv#4]
findContours() algorithm seems to ignore inner contours which makes `8` to be almost identical to `0`.

![figure 1_2017-05-23_12-49-18](https://cloud.githubusercontent.com/assets/1579235/26351114/5d9ba9b0-3fb6-11e7-8dbf-5d7d30f382b3.png)

I believe it's related to the CV_RETR_EXTERNAL parameter. After replacing it with CV_RETR_TREE I've got my inner contours working.

Any other suggestions?

**Comment by skaringa** [comment]
Yes, in your situation may CV_RETR_TREE work better. But possibly you have to adjust to algorithm to find the aligned boxes too in this case.
