### ISSUE TITLE
Training data strange window

### ISSUE THREAD

**Issue by JeremyKeusters** [skaringa/emeocv#7]
Hello Martin,

First of all, thanks for this awesome respository and website. Already learned a lot on OCR & OpenCV because of you.

However, whenever I fire up `./emeocv -i /docker/pics -l` 

I'm getting the following screen.

![training](https://user-images.githubusercontent.com/4648081/36427454-853b9098-164d-11e8-9789-b236cb4e9540.png)

Is this normal? What should appear when training?

Thanks in advance,
Jérémy

**Comment by skaringa** [comment]
The number in the small window top left is the number to train. If its unreadable (like in your case), then probably the segmentation is not optimal (Check with  -a).

**Comment by JeremyKeusters** [comment]
Hi,

Thanks for your answer! I figured out that it's probably because I'm not taking the pictures with this tool and it doesn't run the image processing.  Is there any way to manually run the image processing on an already existing image? Or am I getting this wrong?

Jérémy

**Comment by skaringa** [comment]
I'm not sure if I understand your question fully. In general it is possible to run all functions of the tool either with images from the camera (option -c) or with existing images from a directory (option -i). However the image processing may fail completely if your images are too different from those that I used. Editing the configuration values may help.
